apiVersion: v1
kind: Service
metadata:
  name: apa000ser
spec:
  selector:
    app: apa000kube
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apa000dep
spec:
  selector:
    matchLabels:
      app: apa000kube
  replicas: 1
  template:
    metadata:
      labels:
        app: apa000kube
    spec:
      containers:
      - name: demo
        image: psystar99/api-server
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/nest
        imagePullPolicy: Always